Add aldi.com.au
hhursev/recipe-scrapers pull request #1139
Opened 2024-05-18 09:31 UTC by mlduff

Resolves https://github.com/hhursev/recipe-scrapers/issues/1137

2024-06-03 22:27 UTC, jknndy requested changes

2024-06-03 22:27 UTC, jknndy commented on recipe_scrapers/aldi.py
> +        return title[:recipe_position]
```suggestion
        element = self.soup.select_one("a.tab-nav--link.dropdown--list--link.m-active")
        if element:
            title = element.text
            recipe_position = title.find(" Recipe")
            if recipe_position != -1:
                return title[:recipe_position]
```
replaced `soup.select` with `soup.select_one` to replace the list selection

2024-06-03 22:27 UTC, jknndy commented on recipe_scrapers/aldi.py
> +        return total_time
```suggestion
        return (self.prep_time() or 0) + (self.cook_time() or 0)
```
simplified by using the `or` operator to handle the possible none values. let me know if there was additional reasoning for the original code that required this work around!

2024-06-03 22:27 UTC, jknndy commented on recipe_scrapers/aldi.py
> +        return image.get("src")
```suggestion
        figure = self.soup.find("figure", {"class": "csc-textpic-image csc-textpic-last"})
        if figure:
            image = figure.find("img")
            if image:
                return image.get("src")
        return None
```
simplified the nested checks into a single `if` statement.

2024-06-03 22:27 UTC, jknndy commented on recipe_scrapers/aldi.py
> +        return "\n".join(instructions)
```suggestion
        return "\n".join(li.text.strip() for li in list_element.find_all("li"))
```
changed to use list comprehension to create the instructions list

2024-06-03 22:27 UTC, jknndy commented on recipe_scrapers/aldi.py
> +        return " ".join(parts)
```suggestion
        label_element = self.soup.find("b", string=label)
        if label_element:
            parts = [sibling.strip() for sibling in label_element.find_next_siblings(string=True) if sibling.strip()]
            return " ".join(parts)
        return None
```

changed to use list comprehension to gather the text from the label's next siblings & added `.strip` to cleanup the outputs.

2024-06-03 22:27 UTC, jknndy commented on recipe_scrapers/aldi.py
> +from ._exceptions import ElementNotFoundInHtml
```suggestion
```
related to `total_time` change

2024-06-03 22:36 UTC, jknndy commented
Also don't forget the readme entry!

2024-06-07 14:50 UTC, mlduff commented
> Also don't forget the readme entry!

If only there was a test for that 😉

2024-06-10 21:47 UTC, jknndy approved these changes

2024-06-17 17:49 UTC, jayaddison commented
Thank you @mlduff!

2024-06-17 17:50 UTC, merged