Add scraper for varecha.pravda.sk
hhursev/recipe-scrapers pull request #1165
Opened 2024-07-05 21:22 UTC by jose1711

2024-07-06 19:49 UTC, jknndy requested changes
Hi @jose1711 , thanks for the contribution! 

There are a few changes and additions needed before we can merge;

- [x] [Add a README entry in the support sites section ](https://github.com/hhursev/recipe-scrapers/blob/main/docs/how-to-develop-scraper.md#6-update-the-readme)
- [x] There are a few additional fields that this sites supports that we can include coverage for in the json file. Both `prep_time` & `keywords`
- [x] Address the one code comment

2024-07-06 19:49 UTC, jknndy commented on tests/test_data/varecha.pravda.sk/varechapravdask.json
> +  ],
```suggestion
  ],
  "purpose": null

```

2024-07-08 17:09 UTC, jose1711 commented
Hope I fixed all issues.

2024-07-08 22:24 UTC, jknndy approved these changes

2024-07-11 13:19 UTC, merged

2024-07-15 11:27 UTC, jayaddison commented
This is now available in version `14.58.0` of the library, as published on PyPi.  Thank you!