Fix Gousto (issue #376) by using schema
hhursev/recipe-scrapers pull request #390
Opened 2021-06-13 13:44 UTC by arbrennan

Related to issue #376 

Updated the reference HTML to match live site, revert scraper to use schema.
Updated tests.

My first PR so please let me know if I need to update anything. Also please check the canonical URL test - the schema returns `https://test.example.com/` I'm not sure what to do about this

2021-06-17 01:31 UTC, bfcarpio requested changes
Thank you for the fixes. Just some minor commentary and if it passes tests I'd be happy to merge it in.

2021-06-17 01:31 UTC, bfcarpio commented on tests/test_gousto.py
> +                # "Olive oil",
Is there a reason that these are commented out as opposed to being removed entirely?

2021-06-17 01:31 UTC, bfcarpio commented on tests/test_gousto.py
> +        print(self.harvester_class.canonical_url())
Please remove print statements from tests.

2021-10-10 22:15 UTC, merged

2021-10-10 22:15 UTC, hhursev commented
Merging 🍺  I'll fix the print statements after the merge.