Add support for springlane.de
hhursev/recipe-scrapers pull request #434
Opened 2021-10-03 17:01 UTC by founderio

Uses the default schema parser.

The example recipe is located here: https://www.springlane.de/magazin/rezeptideen/tiramisu-ohne-ei-und-ohne-alkohol/

2021-10-03 20:17 UTC, bfcarpio requested changes
Happy to merge, but it looks like there are some formatting issues that aren't passing our tests. Make sure to run `black` and `flake8` over your changes and then request another review. It should pass the tests then.

2021-10-05 12:53 UTC, founderio commented
Sorry about that, I had my IDE configured to a different formatter.  
This should do it, test passes locally.

2021-10-06 03:49 UTC, bfcarpio approved these changes

2021-10-06 03:49 UTC, bfcarpio commented
Thank you! :beer:

2021-10-06 03:49 UTC, merged